application: footpath-backend
version: 1
runtime: python27
api_version: 1
threadsafe: true

# via http://django-appengine.com/

handlers:
  
- url: /static
  static_dir: static

- url: /.*
  script: main.application
  
libraries:

- name: django
  version: "1.4"
  
env_variables:
  DJANGO_SETTINGS_MODULE: 'django_settings.settings'
